AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ${artifactId}

  Sample SAM Template for ${artifactId}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ${lambdaName}:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ${lambdaName}
      CodeUri: ./target/${artifactId}-${version}-aws-lambda.zip # For the native deployment, use ./target/native/function.zip instead
      Handler: ${package}.lambda.${lambdaName}
      Runtime: java11  # For the native deployment, use provided instead
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        ${lambdaName}Api1:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mult
            Method: post
        ${lambdaName}Api2:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sum
            Method: post
            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ${lambdaName}Api:
    Description: "API Gateway endpoint URL for Prod stage for ${lambdaName} function"
#set( $D = '$' )
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${D}{AWS::Region}.amazonaws.com/Prod/"
  ${lambdaName}:
    Description: "${lambdaName} Function ARN"
    Value: !GetAtt ${lambdaName}.Arn
  ${lambdaName}IamRole:
    Description: "Implicit IAM Role created for ${lambdaName} function"
    Value: !GetAtt ${lambdaName}Role.Arn
